name: Images

on:
  push:
    branches:
      - dev

jobs:
  call-build-and-push:
    name: Call
    uses: CirclesUBI/.github/.github/workflows/build-and-push.yml@main
    with:
      image-name: "pathfinder2
    secrets: inherit
